# Generated by Django 3.0.3 on 2020-03-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank='True', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank='True', max_length=200),
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank='True', max_length=200)),
                ('details', models.TextField()),
                ('keywords', models.CharField(blank='True', max_length=200)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('image', models.ImageField(blank='True', upload_to='images/')),
                ('price', models.FloatField()),
                ('country', models.CharField(blank='True', max_length=20)),
                ('audience', models.CharField(blank='True', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Category')),
            ],
        ),
    ]
