# Generated by Django 3.0.3 on 2020-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_places_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='places',
            new_name='place',
        ),
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.CharField(blank='True', max_length=200),
        ),
    ]
