# Generated by Django 3.0.3 on 2020-04-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200411_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='description',
        ),
    ]
