# Generated by Django 3.0.3 on 2020-04-12 19:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_images_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
