# Generated by Django 3.0.3 on 2020-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_places_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='currency',
            field=models.CharField(choices=[('₺', 'Türk Liraseı'), ('$', 'Dolar'), ('€', 'Euro')], default='dolar', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='visit_hours',
            field=models.CharField(blank='True', max_length=20),
        ),
    ]
