# Generated by Django 3.0.3 on 2020-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20200618_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
