# Generated by Django 3.0.3 on 2020-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20200618_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
