# Generated by Django 3.0.3 on 2020-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200412_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='True', max_length=20)),
                ('email', models.CharField(blank='True', max_length=50)),
                ('subject', models.CharField(blank='True', max_length=50)),
                ('message', models.CharField(blank='True', max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=15)),
                ('ip', models.CharField(blank='True', max_length=20)),
                ('note', models.CharField(blank='True', max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
