# Generated by Django 3.0.3 on 2020-06-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='copyright',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
